### ISSUE TITLE
Replacing occurrences of a string with an empty string fails with Python 3

### ISSUE THREAD

**Issue by timjackson** [kcoyner/rpl#5]
On Fedora 28 ([reported downstream](https://bugzilla.redhat.com/show_bug.cgi?id=1524082) there)

$ echo "abcdef" > test.txt
$ rpl "a" "" test.txt
Really DELETE all occurences of a (case sensitive)? (Y/[N]) Traceback (most recent call last):
  File "/usr/bin/rpl", line 314, in <module>
    main()
  File "/usr/bin/rpl", line 172, in main
    line = raw_input()
NameError: name 'raw_input' is not defined

Tested with commit 5cbaa4b .
$ rpm -q python3
python3-3.6.5-1.fc28.x86_64

Not a problem with Python 2.

Replacing raw_input() with input() on line 172 solves it.

**Comment by timjackson** [comment]
There's also another instance of raw_input() on line 269

**Comment by homeworkprod** [comment]
This specific issue should already be fixed in #1.
